SELECT COLOR, COUNT(COLOR) AS sumcolor 
  FROM AUTO 
  WHERE MARK='BMW' OR MARK='LADA'
  GROUP BY COLOR;

-- .
-- .

SELECT MARK, (SELECT COUNT(REGNUM) FROM AUTO)-COUNT(REGNUM) AS cntregnum
  FROM AUTO
  GROUP BY MARK;
  
SELECT MARK AS mrk, (SELECT COUNT(REGNUM) FROM AUTO WHERE MARK != mrk) AS cntregnum
  FROM AUTO
  GROUP BY MARK;
